//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedMailboxNotifier.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedMailboxNotifier.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared Mailbox Notifier.
        /// </summary>
        public static string AppAttribution {
            get {
                return ResourceManager.GetString("AppAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flag.
        /// </summary>
        public static string ButtonAddCategory {
            get {
                return ResourceManager.GetString("ButtonAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Read.
        /// </summary>
        public static string ButtonMarkRead {
            get {
                return ResourceManager.GetString("ButtonMarkRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reply.
        /// </summary>
        public static string ButtonReply {
            get {
                return ResourceManager.GetString("ButtonReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available.
        /// </summary>
        public static string CategoryAvailable {
            get {
                return ResourceManager.GetString("CategoryAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CategoryCancel {
            get {
                return ResourceManager.GetString("CategoryCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected: {0} of {1}.
        /// </summary>
        public static string CategoryCount {
            get {
                return ResourceManager.GetString("CategoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum {0} categories allowed..
        /// </summary>
        public static string CategoryLimitReached {
            get {
                return ResourceManager.GetString("CategoryLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string CategoryOk {
            get {
                return ResourceManager.GetString("CategoryOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected.
        /// </summary>
        public static string CategorySelected {
            get {
                return ResourceManager.GetString("CategorySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Category Selection.
        /// </summary>
        public static string CategorySelectorTitle {
            get {
                return ResourceManager.GetString("CategorySelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error saving settings: .
        /// </summary>
        public static string ErrorSavingSettings {
            get {
                return ResourceManager.GetString("ErrorSavingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inbox.
        /// </summary>
        public static string InboxFolderName {
            get {
                return ResourceManager.GetString("InboxFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing new mail in .
        /// </summary>
        public static string LogErrorNewMail {
            get {
                return ResourceManager.GetString("LogErrorNewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error during shutdown.
        /// </summary>
        public static string LogErrorShutdown {
            get {
                return ResourceManager.GetString("LogErrorShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error processing notification action: .
        /// </summary>
        public static string LogErrorToastAction {
            get {
                return ResourceManager.GetString("LogErrorToastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to start add-in.
        /// </summary>
        public static string LogFailedToStart {
            get {
                return ResourceManager.GetString("LogFailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Toast notification failed, using BalloonTip.
        /// </summary>
        public static string LogFallbackToBalloon {
            get {
                return ResourceManager.GetString("LogFallbackToBalloon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From: {0}.
        /// </summary>
        public static string LogFrom {
            get {
                return ResourceManager.GetString("LogFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mailbox: {0}.
        /// </summary>
        public static string LogMailbox {
            get {
                return ResourceManager.GetString("LogMailbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitoring {0} shared mailbox(es)..
        /// </summary>
        public static string LogMonitoringCount {
            get {
                return ResourceManager.GetString("LogMonitoringCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New mail received..
        /// </summary>
        public static string LogNewMail {
            get {
                return ResourceManager.GetString("LogNewMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disabled Outlook DesktopAlerts (AllMailboxes mode — add-in handles all notifications)..
        /// </summary>
        public static string LogOutlookAlertsDisabled {
            get {
                return ResourceManager.GetString("LogOutlookAlertsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restored Outlook DesktopAlerts to saved value: {0} (SharedOnly mode — Outlook handles personal mailbox notifications)..
        /// </summary>
        public static string LogOutlookAlertsRestored {
            get {
                return ResourceManager.GetString("LogOutlookAlertsRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved Outlook DesktopAlerts setting ({0}) before disabling. Will be restored when switching to SharedOnly mode..
        /// </summary>
        public static string LogOutlookAlertsSaved {
            get {
                return ResourceManager.GetString("LogOutlookAlertsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changed Outlook PlaySound setting to: {0}..
        /// </summary>
        public static string LogOutlookSoundChanged {
            get {
                return ResourceManager.GetString("LogOutlookSoundChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outlook Shared Mailbox Notifier stopped..
        /// </summary>
        public static string LogShutdown {
            get {
                return ResourceManager.GetString("LogShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outlook Shared Mailbox Notifier started successfully..
        /// </summary>
        public static string LogStartupSuccess {
            get {
                return ResourceManager.GetString("LogStartupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Started monitoring newly added mailbox: {0}.
        /// </summary>
        public static string LogStoreAdded {
            get {
                return ResourceManager.GetString("LogStoreAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopped monitoring removed mailbox: {0}.
        /// </summary>
        public static string LogStoreRemoved {
            get {
                return ResourceManager.GetString("LogStoreRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject: {0}.
        /// </summary>
        public static string LogSubject {
            get {
                return ResourceManager.GetString("LogSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (No subject).
        /// </summary>
        public static string NoSubject {
            get {
                return ResourceManager.GetString("NoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From: 📥{0}.
        /// </summary>
        public static string NotificationFrom {
            get {
                return ResourceManager.GetString("NotificationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New message.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developed with Claude (Anthropic).
        /// </summary>
        public static string SettingsAboutAuthor {
            get {
                return ResourceManager.GetString("SettingsAboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notifications for new emails in shared mailboxes.
        /// </summary>
        public static string SettingsAboutDescription {
            get {
                return ResourceManager.GetString("SettingsAboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на © Ilinskij Aleksandr.
        /// </summary>
        public static string SettingsAboutPublisher {
            get {
                return ResourceManager.GetString("SettingsAboutPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All mailboxes.
        /// </summary>
        public static string SettingsAllMailboxes {
            get {
                return ResourceManager.GetString("SettingsAllMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configure categories....
        /// </summary>
        public static string SettingsConfigureCategories {
            get {
                return ResourceManager.GetString("SettingsConfigureCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sound notification.
        /// </summary>
        public static string SettingsEnableSound {
            get {
                return ResourceManager.GetString("SettingsEnableSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        public static string SettingsGroupAbout {
            get {
                return ResourceManager.GetString("SettingsGroupAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Appearance.
        /// </summary>
        public static string SettingsGroupAppearance {
            get {
                return ResourceManager.GetString("SettingsGroupAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на General.
        /// </summary>
        public static string SettingsGroupGeneral {
            get {
                return ResourceManager.GetString("SettingsGroupGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Monitor Mode.
        /// </summary>
        public static string SettingsMonitorModeGroup {
            get {
                return ResourceManager.GetString("SettingsMonitorModeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings saved. To apply notification changes, please restart Outlook..
        /// </summary>
        public static string SettingsRestartMessage {
            get {
                return ResourceManager.GetString("SettingsRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round icon in notifications.
        /// </summary>
        public static string SettingsRoundAppLogo {
            get {
                return ResourceManager.GetString("SettingsRoundAppLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search local Contacts for sender photos (may slow down notifications).
        /// </summary>
        public static string SettingsSearchContactPhotos {
            get {
                return ResourceManager.GetString("SettingsSearchContactPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shared mailboxes only.
        /// </summary>
        public static string SettingsSharedOnly {
            get {
                return ResourceManager.GetString("SettingsSharedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚠ In this mode, Outlook&apos;s built-in notifications will be disabled to avoid duplicates. Changes will take effect after restarting Outlook..
        /// </summary>
        public static string SettingsWarningAllMailboxes {
            get {
                return ResourceManager.GetString("SettingsWarningAllMailboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✓ Outlook&apos;s built-in notifications for personal mailboxes will be enabled. Changes will take effect after restarting Outlook..
        /// </summary>
        public static string SettingsWarningSharedOnly {
            get {
                return ResourceManager.GetString("SettingsWarningSharedOnly", resourceCulture);
            }
        }
    }
}
